## ***Ejercicios/Resumen de Numpy***

In [2]:
import numpy as np

### 1. Operaciones Básicas con Arrays

Instrucción: Crea dos arrays de 1D con valores enteros y realiza las operaciones de suma, resta, multiplicación, y división entre ellos.

In [3]:
array1 = np.array([10, 20, 30, 40])
array2 = np.array([1, 2, 3, 4])

suma = array1 + array2
resta = array1 - array2
multiplicacion = array1 * array2
division = array1 / array2

print("Suma:", suma)
print("Resta: ", resta)
print("multiplicacion: ", multiplicacion)
print('División: ', division)

Suma: [11 22 33 44]
Resta:  [ 9 18 27 36]
multiplicacion:  [ 10  40  90 160]
División:  [10. 10. 10. 10.]


### 2. Cálculos Estadísticos en Arrays. 
Instrucción: Dado un array de datos, calcula la media, mediana, varianza, y desviación estándar.

In [4]:
import numpy as np

datos = np.array([23, 76, 35, 67, 89, 45, 68, 79, 35])

media = np.mean(datos)
mediana = np.median(datos)
varianza = np.var(datos)
desviacion = np.std(datos)

print("Media: ", media)
print("Mediana: ", mediana)
print("Varianza: ", varianza)
print("Deviación estándar: ", desviacion)

Media:  57.44444444444444
Mediana:  67.0
Varianza:  484.02469135802465
Deviación estándar:  22.000561160071


### 3. Operaciones Matriciales.
Instrucción: Crea dos matrices de 2x2 y realiza las operaciones de suma, resta, multiplicación (producto matricial) y cálculo de la inversa de una de ellas.

In [5]:
import numpy as np

matriz1 = np.array([[1, 2], [3, 4]])
matriz2 = np.array([[5, 6], [7, 8]])

suma_matrices = matriz1 + matriz2
resta_matrices = matriz1 - matriz2
producto_matrices = np.dot(matriz1, matriz2)
inversa_matriz1 = np.linalg.inv(matriz1)

print(suma_matrices,'\n')
print(resta_matrices,'\n')
print(producto_matrices,'\n')
print(inversa_matriz1,'\n')

[[ 6  8]
 [10 12]] 

[[-4 -4]
 [-4 -4]] 

[[19 22]
 [43 50]] 

[[-2.   1. ]
 [ 1.5 -0.5]] 



### 4. Resolución de un Sistema de Ecuaciones lineales

Introducción: Resuelve el sistema de ecuaciones lineales dado por Ax = b, donde A es una matriz 2x2 y b es un vector de 2 elementos

In [6]:
import numpy as np

# Definir la matriz A (2x2)
A = np.array([[2, 3], [1, 2]])

# Definir el vector b (2 elementos)
b = np.array([8, 5])

# Resolver el sistema de ecuaciones A * x = b
x = np.linalg.solve(A, b)

# Imprimir la solución
print("La solución del sistema es:")
print(x)

La solución del sistema es:
[1. 2.]


### 5. Simulación de Datos 

- Genera un array de 1000 números aleatorios que sigan una distribución normal con media 0 y desviación estándar 1. 
- Calcula la media y la desviación estándar del array generado.

In [7]:
datos_simulados = np.random.normal(0, 1, 1000) # (media, stand dev, número de datos aleatorios). 
# Media = el valor alreadedor del cual los datos se distribuyen.
# Stand dev = Desviación estándar, lo que indica cuánto varían los números al rededor de la media
# 1000 = Número de datos aleatorios que se generarán.
print(datos_simulados)

media_simulada = np.mean(datos_simulados)
print('Media de los datos simulados: ', media_simulada)

desviacion_simulada = np.std(datos_simulados)
print('Desviación estándar de los datos simulados', desviacion_simulada)

[-8.17900679e-01  1.24922287e+00 -1.36553746e+00  1.31700642e+00
  5.62272247e-01  6.98577870e-01  3.47753294e-01  2.97898510e-01
 -5.21957414e-01  6.30213154e-01  4.37481790e-01 -5.80476917e-01
  2.88212212e-01 -2.07647707e+00 -1.24596901e+00 -1.00976660e+00
 -1.24542463e+00  2.99298807e-02  7.52771724e-01 -1.39063456e+00
 -1.21823204e-01  8.60531275e-01  1.81510324e+00 -3.42238364e-01
 -6.96906376e-01  1.64631782e-01  1.77701521e+00  1.18518793e+00
 -1.41570594e+00 -7.93498690e-01 -6.02678419e-01 -3.56107386e-01
  1.24513640e+00  1.16644098e+00 -1.20002651e+00  4.26040284e-01
  1.53693305e+00 -1.29090773e+00 -2.04706209e+00 -1.11397240e+00
 -1.40195596e+00 -2.56962554e-01  2.74995847e+00 -5.24507237e-01
 -5.72025292e-01  5.84763479e-01  2.07579766e+00  1.91398777e-01
  1.98541692e-02  4.08742210e-01 -1.71135088e+00  1.10128563e-01
  3.82607646e-01 -1.46467734e-01  1.51987129e+00  5.62848564e-01
 -4.63234895e-02  1.23439160e+00  6.44309336e-01  3.32334669e-01
 -2.68369213e-01  6.28138