### Dimensionalidades - de Escalares a Tensores

Permiten estructuran datos de manera que se puedan realizar calculos complejos y obtener insights valiosos sin perder tiempo.

- Escalar -> Dimensión 0
- Vector -> Dimensión 1
- Tensores -> Varias dimensiones

In [4]:
import numpy as np
escalar = np.array(42) # Se crea un numpy array de dimensión 0 -> escalar.
print(type(escalar)) # Se imprime el tipo de dato: numpy.ndarray
print(escalar) # Imprime el único valor del escalar: 42

<class 'numpy.ndarray'>
42


In [5]:
vector = np.array([30,29,35,31,33,36,42]) # Representa a la dimenensión 1 -> vector
print(vector)

[30 29 35 31 33 36 42]


Al trabajar con DOS VECTORES O MÁS, comenzamos a hablar de MATRICES.

In [6]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]]) #Matriz de dimensión 3x3
print(matrix)
# Si no aplico np.array() el array se imprime en una sola línea y pierde el formato "matriz" que buscamos.
# Numpy permite trabajar en dimensiones (filas y columnas = Matriz/Tensores(multidimensión))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
tensor = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(tensor)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [21]:
array_arange = np.arange(10) #Genera un array de 0 a N-1. Diez números.
print(array_arange)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
eye_matrix = np.eye(3) # np.eye() genera la matriz identidad (toda la diagonal 1 el resto 0)
print(eye_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
diag = np.diag([1,2,3,4,5,6,7]) # np.diag() genera una matriz con diagonal correspondientes a los números del array
print(diag)

[[1 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 0 4 0 0 0]
 [0 0 0 0 5 0 0]
 [0 0 0 0 0 6 0]
 [0 0 0 0 0 0 7]]


In [11]:
random = np.random.random((2,3)) # Genera una matrix 2x3 con un valor random en sus elementos
print(random)

[[0.17942745 0.91166973 0.87989538]
 [0.47497919 0.25277254 0.59334683]]
