### Arrays



**NumPy** proporciona diversas maneras de crear arrays, facilitando la realización de cálculos numéricos y análisis de datos de manera eficiente en Python.

***Diferencias de Listas y Arrays:***

**Rendimiento:** NumPy es mucho más rápido y eficiente para operaciones matemáticas y científicas.

**Tipos de Datos:** NumPy requiere homogeneidad de tipos, mientras que las listas de Python pueden contener múltiples tipos.

**Funcionalidad:** NumPy proporciona una rica funcionalidad específica para cálculos numéricos.

**Slicing e Indexación:** NumPy ofrece herramientas avanzadas para manipular subconjuntos de datos.

NumPy es la mejor opción. Para usos más generales y cuando se necesita mayor flexibilidad en los tipos de datos, las listas de Python son más adecuadas.


In [32]:
import numpy as np


NumPy proporciona diversas maneras de crear arrays, facilitando la realización de cálculos numéricos y análisis de datos de manera eficiente en Python.

1. **Creación de Arrays a partir de Listas**

Podemos crear un array a partir de una lista o una lista de listas:

In [33]:
# Array unidimensional
array_1d = np.array([1, 2, 3, 4])

# Array bidimensional
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

2. **Creación de Arrays con Funciones Predefinidas**

NumPy proporciona funciones predefinidas para crear arrays de manera más rápida y conveniente:

In [34]:
# np.zeros(): Crea un array lleno de ceros.
zeros_array = np.zeros((3, 3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [35]:
# np.ones(): Crea un array lleno de unos.
ones_array = np.ones((2, 4))
print(ones_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [36]:
# np.arange(): Crea un array con una secuencia de números.
range_array = np.arange(0, 10, 2)  # [0, 2, 4, 6, 8]
print(range_array)

[0 2 4 6 8]


In [37]:
# np.linspace(): Crea un array con números igualmente espaciados.
linspace_array = np.linspace(0, 1, 5)  # [0., 0.25, 0.5, 0.75, 1.]
print(linspace_array)

[0.   0.25 0.5  0.75 1.  ]


3. **Especificando Tipos de Datos (Datatypes)**

Al crear un array, podemos especificar el tipo de datos que contendrá utilizando el parámetro dtype. Esta especificación es crucial para la eficiencia y precisión en cálculos numéricos. Aquí se detallan algunos de los tipos de datos más comunes:

- **int32**: Entero de 32 bits.
- **float32**: Número de punto flotante de 32 bits.
- **float64**: Número de punto flotante de 64 bits (por defecto para números flotantes en NumPy).
- **bool**: Valores booleanos (True o False).
- **complex64**: Número complejo de 64 bits.
- **complex128**: Número complejo de 128 bits.
- **str**: Cadenas de texto.

Podemos especificar estos tipos de datos al crear el array utilizando el parámetro dtype:

In [38]:
# Array de enteros
int_array = np.array([1, 2, 3], dtype='int32')

# Array de flotantes
float_array = np.array([1.0, 2.0, 3.0], dtype='float32')

# Array de booleanos
bool_array = np.array([True, False, True], dtype='bool')

# Array de números complejos
complex_array = np.array([1+2j, 3+4j], dtype='complex64')

# Array de cadenas de texto
str_array = np.array(['a', 'b', 'c'], dtype='str')

Algunos de estos tipos también pueden ser especificados con abreviaturas en el parámetro ***dtype***. Por ejemplo, ***'d'*** es equivalente a ***float64***, que es el tipo de datos de punto flotante de 64 bits en NumPy:

In [39]:
array = np.array([[1,2,3],[4,5,6]]) # Matriz 2x3
print(array.ndim) # Sirve para conocer las dimensiones del array
print(array.shape) # Sirve para conocer el ORDEN de la matriz "NxN"
print(array.dtype) # Objeto de Numpy que describe el type de los elementos que tenemos dentro del array. (Ver lo siguiente)

2
(2, 3)
int32


In [40]:
z = np.array(3, dtype=np.uint8) # Se especifica el tipo de dato
print(z)
print(type(z))

3
<class 'numpy.ndarray'>


In [41]:
double_array = np.array([1,2,3], dtype='d') # Especifica un float64 con 'd'
print(double_array)

[1. 2. 3.]


In [42]:
z = z.astype(np.float64) # Método astype() permite cambiar el formato de una variable
print(z)
print(type(z))

3.0
<class 'numpy.ndarray'>


4. **NaN (Not a Number)**

***NaN*** es un valor especial utilizado para representar datos que no son números, especialmente en el contexto de operaciones matemáticas que no tienen un resultado definido. Por ejemplo, la división de cero por cero (0/0) o la raíz cuadrada de un número negativo.

In [43]:
nan_array = np.array([1, 2, np.nan, 4])
print(nan_array)

[ 1.  2. nan  4.]


----

Operaciones matemáticas y estadísticas

In [44]:
array = np.array([[1,2,3],[4,5,6]])
add = np.sum(array) 
print(add)

21


In [45]:
array = np.array([[1,2,3],[4,5,6]])
sum = np.sum(array) # suma todos los elementos del array
print(sum)

21


In [46]:
mean = np.mean(array) # Calcular la media
print(mean)

3.5


In [47]:
std = np.std(array) # Desviación estándar
print(std)

1.707825127659933
