In [ ]:
import numpy as np

- Indexación clásica, mediante el índice del array

In [34]:
# Accedemos mediante el índice
array = np.array([12, 20, 30, 40, 50])
print(array[1])
print(array[-1])
print(array[1:4])
print(array[0:9]) # Si me excedo en la posición final del array, muestra el último.

20
50
[20 30 40]
[12 20 30 40 50]
[]


- Indexacción Booleana

In [42]:
array = np.array([12, 20, 30, 40, 50])
bool_index = array > 25 # Condición
print(bool_index) # Devuelve booleanos que cumplen con la condición
print(array[bool_index]) # Devuelve los elementos que cumplen con la condición

[False False  True  True  True]
[30 40 50]


- Indexación por Lista

In [43]:
array = np.array([12, 20, 30, 40, 50])
index = [2, 3, 4]
print(array[index]) # Le paso una LISTA de índices

[30 40 50]


---

Accediendo a un array de múltiples dimensiones:

In [46]:
# Primero creamos un array con elementos random
array = np.random.randint(1, 10, size=(3,3))
print(array)

# Ingresamos a la posición expresada por las coordenadas (0, 1) = (fila, columna)
print(array[1, 2])

[[9 1 3]
 [9 6 8]
 [3 3 9]]
8


Puedo realizar un "corte" en una matriz y extraer esta porción:

In [48]:
print(array[:2, :2]) # Dos primeras filas / Dos primeras columnas

[[9 1]
 [9 6]]


----

**Ejercicios para practicar Indexación y Slicing:**

1. Acceder a elementos específicos:

    - Crea un arreglo de 10 números y accede al cuarto y penúltimo elemento usando índices positivos y negativos.

2. Slicing de arreglos:

    - Dado un arreglo de números del 1 al 20, extrae los elementos entre las posiciones 3 y 7, y luego los elementos de las últimas 5 posiciones.

3. Indexing con booleanos:

    - Crea un arreglo de números aleatorios entre 0 y 100. Usa una expresión booleana para acceder solo a los números mayores a 50.

4. Indexación con múltiples índices:

    - Dado un arreglo de 8 elementos, crea una lista de índices para acceder a los elementos en las posiciones 1, 4, y 6.

5. Matrices bidimensionales:

    - Genera una matriz 4x4 de números aleatorios entre 10 y 50, y accede a la submatriz de 2x2 ubicada en la esquina inferior derecha.