### ¿Qué es broadcasting en NumPy?

Broadcasting es una funcionalidad poderosa en NumPy que permite realizar operaciones aritméticas en arrays de diferentes tamaños y formas de manera eficiente. En lugar de iterar sobre cada elemento de los arrays para realizar las operaciones, NumPy extiende automáticamente los arrays más pequeños para que coincidan con las dimensiones de los más grandes, sin duplicar datos. Esto no solo optimiza el uso de la memoria, sino que también acelera significativamente las operaciones.

El broadcasting permite que las operaciones entre arrays de diferentes dimensiones se realicen como si todos los arrays tuvieran la misma forma. NumPy extiende los arrays más pequeños a la forma del más grande de manera implícita, facilitando las operaciones sin necesidad de copiar los datos.

#### **Aplicaciones de Broadcasting**

- **Aplicación de Descuentos:** Supongamos que tenemos un array que representa los precios de varios productos y otro array con un descuento porcentual que se aplica a todos los productos. Con broadcasting, podemos aplicar el descuento sin necesidad de un bucle explícito.

In [1]:
import numpy as np

prices = np.array([100, 200, 300])
discount = np.array([0.9])
discounted_prices = prices * discount
print(discounted_prices)

[ 90. 180. 270.]


- **Operaciones con Arrays Multidimensionales:** Podemos realizar operaciones elementales entre arrays de diferentes dimensiones.

In [2]:
a = np.array([[0.0, 0.0, 0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])
b = np.array([1.0, 2.0, 3.0])
result = a + b
print(result)

[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [12]:
# Otro ejemplo con arrays multidimencionales
prices = np.random.randint(100, 500, size=(3, 3))
discount = np.array([10, 20, 30])
discount_prices = prices + discount
print(prices)
print('Con descuento aplicado:')
print(discount_prices)

[[127 132 241]
 [261 167 277]
 [347 105 135]]
Con descuento aplicado:
[[137 152 271]
 [271 187 307]
 [357 125 165]]


#### **Importancia del Broadcasting**
Broadcasting es crucial porque permite escribir código más conciso y legible, evitando bucles explícitos y aprovechando las optimizaciones internas de NumPy para realizar operaciones de manera rápida y eficiente. Esto es especialmente útil en análisis de datos y aprendizaje automático, donde se manejan grandes volúmenes de datos y se requieren cálculos rápidos.

#### **Reglas de Broadcasting**

Para que el broadcasting funcione, las dimensiones de los arrays deben cumplir ciertas reglas:

Comparación desde la Última Dimensión: Las dimensiones se comparan desde la última hacia la primera.
Dimensiones Compatibles: Dos dimensiones son compatibles si son iguales o si una de ellas es 1.

Ejemplos:

- **Escalar y Array 1D**

In [3]:
a = np.array([1, 2, 3])
b = 2
result = a * b
print(result)

[2 4 6]


- **Array 1D y Array 2D:**

In [6]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([1, 0, 1])
result = a * b
print(result)

[[1 0 3]
 [4 0 6]
 [7 0 9]]


- **Array 2D y Array 3D:**

In [7]:
a = np.array([[[1], [2], [3]], [[4], [5], [6]]])
b = np.array([1, 2, 3])
result = a * b
print(result)

[[[ 1  2  3]
  [ 2  4  6]
  [ 3  6  9]]

 [[ 4  8 12]
  [ 5 10 15]
  [ 6 12 18]]]


Broadcasting en NumPy es una técnica esencial para realizar operaciones aritméticas de manera eficiente en arrays de diferentes tamaños y formas. Entender y aplicar las reglas de broadcasting permite escribir código más limpio y optimizado, crucial para tareas de análisis de datos y aprendizaje automático.

Explora estas funcionalidades y descubre cómo broadcasting puede mejorar la eficiencia de tus cálculos en Python.

---

#### Más ejemplos:

Buscar en todo el array si existen elementos mayores a 9

In [13]:
array = np.array([1, 2, 3, 4, 5])
print(np.all(array > 9))

False


Buscar algún elemento que sea mayor a 4

In [14]:
print(np.any(array > 4))

True


Concatenar numpyarrays con la función concatenate()

In [16]:
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
concatenated = np.concatenate((array_a, array_b))
print(concatenated)

[1 2 3 4 5 6]


Vertical Stacking: apilar arrays verticalmente

In [17]:
stacked_v = np.stack((array_a, array_b))
print(stacked_v)

[[1 2 3]
 [4 5 6]]


Horizontal Stacking: apilar arrays horizontalmente

In [18]:
stacked_v = np.hstack((array_a, array_b))
print(stacked_v)

[1 2 3 4 5 6]


Obtener porciones de arrays

In [23]:
array_c = np.arange(1, 10)
split_array = np.split(array_c, 3)
print(array_c) # Array base
print(split_array) # Las 3 porciones/divisiones del array base

[1 2 3 4 5 6 7 8 9]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
