Con Numpy se pueden **buscar elementos únicos y contar su frecuencia**. Esto puede ser de ayuda para, por ejemplo, encontrar una opinión y la repetición de la misma en una cantidad de usuarios que participaron de una encuesta.

In [3]:
import numpy as np

Mostrar los elementos únicos:

In [5]:
servey_responses = np.array(["bueno", "excelente", "malo",
                             "bueno", "malo", "excelente",
                             "bueno", "bueno", "malo", "excelente"])
print(np.unique(servey_responses))

['bueno' 'excelente' 'malo']


Mostrar la cantidad de elementos únicos:

In [6]:
unique_elements, count = np.unique(servey_responses, return_counts=True)
print(unique_elements) # Primero imprimo los elementos únicos
print(count) # Luego la cantidad de cada elemento

['bueno' 'excelente' 'malo']
[4 3 3]


En Numpy es posible trabajar con **Vistas** y **Copias**:

- Una **vista** (view) en Numpy es simplemente una referencia a los mismos datos en la memoria. Cuando modificas la vista, los datos originales también cambian, ya que ambos comparten el mismo espacio de memoria. Esto es útil cuando quieres ahorrar memoria y tiempo, ya que no necesitas duplicar el array completo, solo trabajar con una referencia.

In [12]:
import numpy as np
a = np.array([1, 2, 3, 4])
b = a.view()
b[0] = 10  # Esto también modifica 'a'
print(a)  # Salida: [10, 2, 3, 4]

[10  2  3  4]


- Una **copia** (copy) crea un nuevo array con los mismos valores que el original, pero en un espacio de memoria diferente. Si modificas la copia, el array original no se verá afectado. Esto es útil cuando deseas manipular datos sin alterar el array original.

In [13]:
c = a.copy()
c[0] = 20  # Esto no afecta 'a'
print(a)  # Salida: [10, 2, 3, 4]
print(c)  # Salida: [20, 2, 3, 4]

[10  2  3  4]
[20  2  3  4]
