Operaciones básicas de álgebra lineal: Numpy optimiza y simplifica estas operaciones en Python.

In [3]:
import numpy as np

Suma de matrices/arrays:

In [9]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Suma
sum = A + B
print(A,'\n')
print(B,'\n')
print(sum,'\n')

[[1 2]
 [3 4]] 

[[5 6]
 [7 8]] 

[[ 6  8]
 [10 12]] 



Multiplicación de arrays/matrices:

In [10]:
# Multiplicación
product = np.dot(A, B)
print(product)

[[19 22]
 [43 50]]


Determinante de una matriz:

In [22]:
# Determinante
A = np.array([[1, 2], [3, 4]])
det_A = np.linalg.det(A)
print(f'Determinante de A:\n{det_A}\n')

# Inversa de la matriz A
inv_A = np.linalg.inv(A)
print(f'Inversa de la Matriz:\n{inv_A}')

Determinante de A:
-2.0000000000000004

Inversa de la Matriz:
[[-2.   1. ]
 [ 1.5 -0.5]]


También podemos resolver un sistema de ecuaciones:

In [23]:
# Resolver ecuación lineal -> ax = b
A = np.array([[1, 2], [3, 4]])
b = np.array([9, 11])
x = np.linalg.solve(A, b)
print(x)

[-7.  8.]
